nginx_worker_process: 8
nginx_error_log: "/var/log/nginx/error.log warn"
nginx_worker_connections: 1024
nginx_access_log: "/var/log/nginx/access.log main"
nginx_debug_log: "/var/log/nginx/debug.log debug"
nginx_sendfile: "on"
nginx_sendfile_max_chunk: "1m"
nginx_tcp_nopush: "on"
nginx_tcp_nodelay: "on"
nginx_keepalive_timeout: 65
nginx_backlog: 4096
